### ISSUE TITLE
Document OpenCTI processes

### ISSUE THREAD

**Issue by JCKelley-CYBR** [24SP-UNO-Capstone/Milestone1#11]

**Comment by JCKelley-CYBR** [comment]
Utilize documentation and sources to identify OpenCTI procedures for connecting sources, setting up the application, and troubleshooting steps.

**Comment by DillonPetschke** [comment]
https://github.com/24SP-UNO-Capstone/Milestone1/blob/main/OpenCTI%20-%20Docker.md
